
package vista;

import java.awt.Dimension;

/**
 *
 * @author hanas
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(700, 700));
        this.setExtendedState(FrmMenu.MAXIMIZED_BOTH);//creo que este es para el maximo de la pantalla
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de ventas");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_nuevo_usuario = new javax.swing.JMenuItem();
        jMenuItem_gestionar_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_nuevo_proveedor = new javax.swing.JMenuItem();
        jMenuItem_gestionar_proveedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem_gestionar_producto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_nueva_factura = new javax.swing.JMenuItem();
        jMenuItem_gestionar_factura = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu_cerrar_sesion = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem20.setText("jMenuItem20");

        jMenuItem22.setText("jMenuItem22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu1.setMinimumSize(new java.awt.Dimension(282, 60));
        jMenu1.setPreferredSize(new java.awt.Dimension(230, 60));

        jMenuItem_nuevo_usuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_nuevo_usuario.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem_nuevo_usuario.setText("Nuevo Usuario");
        jMenuItem_nuevo_usuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_nuevo_usuario);

        jMenuItem_gestionar_usuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_gestionar_usuario.setText("Gestionar Usuario");
        jMenuItem_gestionar_usuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gestionar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_gestionar_usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Proveedor");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu2.setMinimumSize(new java.awt.Dimension(230, 60));
        jMenu2.setPreferredSize(new java.awt.Dimension(240, 60));

        jMenuItem_nuevo_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_nuevo_proveedor.setText("Crear Proveedor");
        jMenuItem_nuevo_proveedor.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu2.add(jMenuItem_nuevo_proveedor);

        jMenuItem_gestionar_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_gestionar_proveedor.setText("Gestionar Proveedor");
        jMenuItem_gestionar_proveedor.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gestionar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_proveedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_gestionar_proveedor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Producto");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu3.setMinimumSize(new java.awt.Dimension(250, 60));
        jMenu3.setPreferredSize(new java.awt.Dimension(240, 60));

        jMenuItem_nuevo_producto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_nuevo_producto.setText("Crear Producto");
        jMenu3.add(jMenuItem_nuevo_producto);

        jMenuItem_gestionar_producto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_gestionar_producto.setText("Gestionar Prodcto");
        jMenuItem_gestionar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_productoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_gestionar_producto);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Facturar");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu4.setMinimumSize(new java.awt.Dimension(240, 60));
        jMenu4.setPreferredSize(new java.awt.Dimension(250, 60));

        jMenuItem_nueva_factura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_nueva_factura.setText("Crear Factura");
        jMenuItem_nueva_factura.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu4.add(jMenuItem_nueva_factura);

        jMenuItem_gestionar_factura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem_gestionar_factura.setText("Gestionar Factura");
        jMenuItem_gestionar_factura.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionar_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_facturaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gestionar_factura);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu5.setMinimumSize(new java.awt.Dimension(260, 60));
        jMenu5.setPreferredSize(new java.awt.Dimension(240, 60));

        jMenu_cerrar_sesion.setText("Cerrar Sesión");
        jMenu_cerrar_sesion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu_cerrar_sesion.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu5.add(jMenu_cerrar_sesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_usuarioActionPerformed
     FormularioRegistrar registro = new FormularioRegistrar();
    registro.setVisible(true);
    this.dispose(); // Opcional, cierra la ventana de login
    }//GEN-LAST:event_jMenuItem_nuevo_usuarioActionPerformed

    private void jMenuItem_gestionar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_usuarioActionPerformed
       InterGestionarUsuario gestionarUsuarios = new InterGestionarUsuario();
    gestionarUsuarios.setVisible(true);
   
    
    }//GEN-LAST:event_jMenuItem_gestionar_usuarioActionPerformed

    private void jMenuItem_gestionar_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_gestionar_facturaActionPerformed

    private void jMenuItem_gestionar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_gestionar_productoActionPerformed

    private void jMenuItem_gestionar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_gestionar_proveedorActionPerformed

    /**+++
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    System.out.println("Iniciando aplicación...");

    java.awt.EventQueue.invokeLater(() -> {
        System.out.println("Creando instancia de FrmMenu...");
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        System.out.println("FrmMenu debería estar visible.");
    });

    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem_gestionar_factura;
    private javax.swing.JMenuItem jMenuItem_gestionar_producto;
    private javax.swing.JMenuItem jMenuItem_gestionar_proveedor;
    private javax.swing.JMenuItem jMenuItem_gestionar_usuario;
    private javax.swing.JMenuItem jMenuItem_nueva_factura;
    private javax.swing.JMenuItem jMenuItem_nuevo_producto;
    private javax.swing.JMenuItem jMenuItem_nuevo_proveedor;
    private javax.swing.JMenuItem jMenuItem_nuevo_usuario;
    private javax.swing.JMenu jMenu_cerrar_sesion;
    // End of variables declaration//GEN-END:variables
}
